# Generated by Django 3.2.16 on 2022-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='вес')),
                ('length', models.IntegerField(verbose_name='длина')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('city_to', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Город отправки')),
                ('subject_to', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Субъект РФ отправки посылки')),
                ('district_to', models.CharField(blank=True, default='', help_text='Максимум 50 символов', max_length=50, verbose_name='Округ отправки посылки')),
                ('city_from', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Город получения посылки')),
                ('subject_from', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='Субъект РФ получения посылки')),
                ('district_from', models.CharField(blank=True, default='', help_text='Максимум 50 символов', max_length=50, verbose_name='Округ получения посылки')),
            ],
        ),
    ]
