# Generated by Django 3.2.16 on 2022-12-22 15:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('another_link', models.URLField(blank=True, help_text='Добавьте ссылку на сайт с отзывами об этой службе', null=True, verbose_name='другие отзывы')),
            ],
            options={
                'verbose_name': 'курьерская служба',
                'verbose_name_plural': 'курьерские службы',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('text', ckeditor.fields.RichTextField(help_text='Подробно расскажите о впечатлениях от данной курьерской службы', verbose_name='описание')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='дата написания')),
                ('grade', models.IntegerField(blank=True, choices=[(1, 'Отрицательная'), (2, 'Нейтральная'), (3, 'Положительная')], null=True, verbose_name='оценка')),
                ('delivery', models.ForeignKey(help_text='Выберите курьерскую службу', on_delete=django.db.models.deletion.CASCADE, to='response.delivery', verbose_name='курьерская служба')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='лайк')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение к отзыву')),
                ('response', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.response', verbose_name='отзыв')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(help_text='Напишите свой комментарий', verbose_name='текст')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.response', verbose_name='отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
