# Generated by Django 3.2.16 on 2022-12-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='blank-avatar.jpeg', upload_to='previews/%Y/%m/%d', verbose_name='аватарка'),
        ),
    ]
