# Generated by Django 3.2.16 on 2022-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='previews/%Y/%m/%d', verbose_name='аватарка'),
        ),
    ]
